HotSpot_compile

diff --git a/src/main/java/com/deepblue/chapter_02_compile/HotSpot目录下编译脚本 b/src/main/java/com/deepblue/chapter_02_compile/HotSpot目录下编译脚本
--- a/src/main/java/com/deepblue/chapter_02_compile/HotSpot目录下编译脚本
+++ b/src/main/java/com/deepblue/chapter_02_compile/HotSpot目录下编译脚本
@@ -10,6 +10,38 @@
 
 ## apache-ant下载链接 https://ant.apache.org/ 在里面查找就OK了
 
+[root@localhost soft]# cd jdk1.6.0_35/
+[root@localhost jdk1.6.0_35]# pwd
+/home/yangjianwei/mywork/soft/jdk1.6.0_35
+[root@localhost jdk1.6.0_35]# cd ../
+[root@localhost soft]# cd apache-ant-1.8.4/
+[root@localhost apache-ant-1.8.4]# pwd
+/home/yangjianwei/mywork/soft/apache-ant-1.8.4
+
+
+
+export JAVA_HOME=/home/yangjianwei/mywork/soft/jdk1.6.0_35
+export JRE_HOME=/home/yangjianwei/mywork/soft/jdk1.6.0_35/jre
+export CLASSPATH=$JRE_HOME/lib/rt.jar:$JRE_HOME/lib/ext
+export PATH=$PATH:$JRE_HOME/bin:$JAVA_HOME/bin
+
+export ANT_HOME=/home/yangjianwei/mywork/soft/apache-ant-1.8.4
+export PATH=$PATH:$ANT_HOME/bin
+
+卸载旧版本的JDK：
+1. 确定JDK的版本：
+rpm -qa | grep jdk
+rpm -qa | grep gcj
+
+yum -y remove java-1.8.0-openjdk-1.8.0.161-2.b14.el7.x86_64
+yum -y remove copy-jdk-configs-3.3-2.el7.noarch
+yum -y remove java-1.7.0-openjdk-headless-1.7.0.171-2.6.13.2.el7.x86_64
+yum -y remove java-1.8.0-openjdk-headless-1.8.0.161-2.b14.el7.x86_64
+
+
+
+
+
 ############################################################ 以下为启动脚本 在HotSpot目录下 #####################################################
 #!/bin/bash
 export LANG=C
@@ -22,7 +54,7 @@ export ALT_JDK_IMPORT_PATH="/home/yangjianwei/mywork/soft/jdk1.6.0_35"
 export ANT_HOME="/home/yangjianwei/mywork/soft/apache-ant-1.8.4"
 
 #导入PATH
-export PATH=""
+export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/yangjianwei/mywork/soft/jdk1.6.0_35/jre/bin:/home/yangjianwei/mywork/soft/jdk1.6.0_35/bin:/home/yangjianwei/mywork/soft/apache-ant-1.8.4/bin:/home/yangjianwei/.local/bin:/home/yangjianwei/bin"
 
 #其他配置
 export HOTSPOT_BUILD_JOBS=5
@@ -32,4 +64,58 @@ export ALT_OUTPUTDIR=/home/openjdk/hotspot/build_jvm
 
 #以下为执行命令
 cd make
-make DEBUG_BINARIES=true jvmg jvmg1 2>&1 | tee /home/openjdk/hotspot/build_jvm/hotspot_debug.log
+make DEBUG_BINARIES=true VM_TARGET=product generic_build2 jvmg jvmg1 2>&1 | tee /home/openjdk/hotspot/build_jvm/hotspot_debug.log
+
+
+
+make[3]: *** [check_j2se_version] Error 1
+make[3]: Leaving directory `/home/openjdk/hotspot/build/linux'
+make[2]: *** [linux_i486_compiler2/debug] Error 2
+make[2]: Leaving directory `/home/openjdk/hotspot/build/linux'
+make[1]: *** [generic_build2] Error 2
+make[1]: Leaving directory `/home/openjdk/hotspot/make'
+
+
+
+
+
+[yangjianwei@localhost ~]$ cat /home/openjdk/hotspot/build_jvm/hotspot_debug.log
+/bin/sh: line 0: cd: /java/re/j2se/1.6.0/latest/binaries/linux-i586: No such file or directory
+cd /home/openjdk/hotspot/make; \
+make VM_TARGET=jvmg generic_build2
+/bin/sh: line 0: cd: /java/re/j2se/1.6.0/latest/binaries/linux-i586: No such file or directory
+make[1]: Entering directory `/home/openjdk/hotspot/make'
+mkdir -p /home/openjdk/hotspot/build/linux
+cd /home/openjdk/hotspot/build/linux; \
+    make -f /home/openjdk/hotspot/make/linux/Makefile \
+	       JAVA_HOME=/home/openjdk/hotspot/make OUTPUTDIR=/home/openjdk/hotspot/build/linux GAMMADIR=/home/openjdk/hotspot MAKE_VERBOSE=y HOTSPOT_RELEASE_VERSION=21.0-b17 JRE_RELEASE_VERSION="1.7.0" HOTSPOT_BUILD_VERSION=internal jvmg
+/bin/sh: line 0: cd: /java/re/j2se/1.6.0/latest/binaries/linux-i586: No such file or directory
+make[2]: Entering directory `/home/openjdk/hotspot/build/linux'
+make -f /home/openjdk/hotspot/make/linux/Makefile checks
+/bin/sh: line 0: cd: /java/re/j2se/1.6.0/latest/binaries/linux-i586: No such file or directory
+make[3]: Entering directory `/home/openjdk/hotspot/build/linux'
+/java/re/j2se/1.6.0/latest/binaries/linux-i586/bin/javap javax.xml.transform.TransformerFactory > /dev/null 2>&1; \
+if [ $? -ne 0 ]; then \
+   /java/re/j2se/1.6.0/latest/binaries/linux-i586/bin/java -version; \
+  echo "*** An XSLT processor (J2SE 1.4.x or newer) is required" \
+  "to bootstrap this build" 1>&2; \
+  exit 1; \
+fi
+/bin/sh: line 2: /java/re/j2se/1.6.0/latest/binaries/linux-i586/bin/java: No such file or directory
+*** An XSLT processor (J2SE 1.4.x or newer) is required to bootstrap this build
+make[3]: *** [check_j2se_version] Error 1
+make[3]: Leaving directory `/home/openjdk/hotspot/build/linux'
+make[2]: *** [linux_i486_compiler2/debug] Error 2
+make[2]: Leaving directory `/home/openjdk/hotspot/build/linux'
+make[1]: *** [generic_build2] Error 2
+make[1]: Leaving directory `/home/openjdk/hotspot/make'
+make: *** [jvmg] Error 2
+
+
+freetypecheck.c:32:22: fatal error: ft2build.h: No such file or directory
+ #include "ft2build.h"
+compilation terminated.
+make[2]: *** [/home/openjdk/build/linux-amd64/btbins/freetype_versioncheck] Error 1
+make[1]: Leaving directory `/home/openjdk/jdk/make'
+
+
